// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO4qQepLR9Su2T8aDlYosF8O7GPDPAYzU',
    appId: '1:363090369469:web:76886678cc1642d97650d4',
    messagingSenderId: '363090369469',
    projectId: 'practice-flutter-5b17b',
    authDomain: 'practice-flutter-5b17b.firebaseapp.com',
    storageBucket: 'practice-flutter-5b17b.appspot.com',
    measurementId: 'G-J08WLK61YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYi7EsZ6IyXF0BPyTIeHT6LnFoF-4VMMk',
    appId: '1:363090369469:android:dd72b92b38ac75a57650d4',
    messagingSenderId: '363090369469',
    projectId: 'practice-flutter-5b17b',
    storageBucket: 'practice-flutter-5b17b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCwCLrGFkB0t5MkE_PtTUyWj8CPiTLYQ',
    appId: '1:363090369469:ios:37245586315e53df7650d4',
    messagingSenderId: '363090369469',
    projectId: 'practice-flutter-5b17b',
    storageBucket: 'practice-flutter-5b17b.appspot.com',
    androidClientId: '363090369469-ia4qp7vajgpjt0ef7c6mpubdf0f7vldg.apps.googleusercontent.com',
    iosClientId: '363090369469-bkqm3e03eshr84u0fc9apjr6fdqputc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCwCLrGFkB0t5MkE_PtTUyWj8CPiTLYQ',
    appId: '1:363090369469:ios:62e92d75fb1428d07650d4',
    messagingSenderId: '363090369469',
    projectId: 'practice-flutter-5b17b',
    storageBucket: 'practice-flutter-5b17b.appspot.com',
    androidClientId: '363090369469-ia4qp7vajgpjt0ef7c6mpubdf0f7vldg.apps.googleusercontent.com',
    iosClientId: '363090369469-119m3u2mp56eh8vcfim4le9i7q5gd67p.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFlutter.RunnerTests',
  );
}
